spring:
  application:
    name: booking-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/checkinn_booking}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  config:
    import: "optional:configserver:"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    show-sql: false
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  cloud:
    config:
      uri: http://localhost:8888

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: ${PORT:8084}

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG

# Feign Client configuration
user-service:
  url: ${USER_SERVICE_URL:http://localhost:8082}

grpc:
  server:
    port: 9093

hotel:
  service:
    url: ${HOTEL_SERVICE_URL:http://hotel-service}

app:
  rabbit:
    exchange: ${RABBIT_EXCHANGE:hotel.events}

vnpay:
  tmnCode: W0MI1ZMG
  hashSecret: W5AF1T7ITXWOP1PC960RXCWYW0UWBBYZ
  returnUrl: http://localhost:3000/booking/payment/return
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
